#!/usr/bin/env bash
# bash script that  installs the 'ufw' firewall and,
# setup a few rules on 'web-01'

sudo apt-get install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 8080/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
