#!/usr/bin/env bash
# bash script that configures 'nginx' to run & listen to port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
sleep 2
service nginx status|grep-q "not running" && echo "*nginx is not running"||true



























