#!/bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file=$1
ip=$2
username=$3
ssh_key=$4

# Disable strict host key checking
ssh -o StrictHostKeyChecking=no $username@$ip

# Transfer the file to the user home directory
scp $file $username@$ip:~/

# Disconnect from the server
ssh -o StrictHostKeyChecking=no $username@$ip exit
